sudo: false

matrix:
  include:
    - language: python
      python: 2.7

      cache:
        directories:
          - "~/.platformio"

      install:
        - pip install -U platformio

      script:
        - (cd rover && platformio run)

    - language: crystal

      cache:
        directories:
          - "~/.cache/shards"

      install:
        - (cd groundstation && shards)

      script:
        - (cd groundstation && crystal spec)
        - (cd groundstation && shards build)
        - (cd groundstation && crystal tool format --check src spec)
