sudo: false

matrix:
  include:
    - language: python
      python: 2.7

      cache:
        directories:
          - "~/.platformio"

      install:
        - pip install -U platformio

      script:
        - (cd rover && platformio run)
